trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: subscription
    type: string
    displayName: 'Environment Name'
    default: 'Dev'
    values:
      - Dev
      - Test
      - Stage

steps:
  - task: TerraformInstaller@0
    displayName: "Terraform install"
    inputs: 
      terraformVersion: '1.7.0'

  - script: |
      echo "##vso[task.setvariable variable=config_file_path]$(Build.SourcesDirectory)/Environments/$(parameters.subscription).auto.tfvars"
    displayName: 'Set config_file_path variable'

  - task: TerraformTaskV4@4
    displayName: "Terraform init"
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Pay-As-You-Go(1)(f510d486-a17f-44f2-a1c4-63a7186e923c)'
      backendAzureRmResourceGroupName: 'azuredevops'
      backendAzureRmStorageAccountName: 'azuredevops4544'
      backendAzureRmContainerName: 'azuredevopscontainer'
      backendAzureRmKey: 'terraform.tfstate'

  - script: |
      /opt/hostedtoolcache/terraform/1.7.0/x64/terraform plan -var-file=$(config_file_path) -detailed-exitcode
    displayName: 'Terraform plan'

  - task: PublishBuildArtifacts@1
    displayName: "publish build artifacts"
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/terraform.tfplan'
      artifactName: 'terraformPlan'
      publishLocation: 'Container'

  - task: TerraformTaskV4@4
    displayName: "Terraform apply"
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'Pay-As-You-Go(1)(f510d486-a17f-44f2-a1c4-63a7186e923c)'
